docs/package.json

Same changes as PR #61, but this time branched off develop.

update dependency versions for security

---

docs/package-lock.json

This actually fixes the problem, because I missed a step when I updated the `package.json` file in an earlier PR.

update package-lock file

---

Gemfile
urbanopt-scenario-gem.gemspec

Fix rack version temporarily to work with Ruby 2.2.4

---

Rakefile
lib/measures/default_feature_reports/LICENSE.md

Include 2020 in copyright dates

update copyright dates to include 2020

---

Jenkinsfile

Updating CI workflow to support ruby 2.2.4 and bundler 1.x.

update Jenkinsfile for ruby 2.2.4 and bundler 1.x support

---

lib/measures/default_feature_reports/measure.rb
lib/urbanopt/scenario/default_reports/schema/README.md
lib/urbanopt/scenario/default_reports/timeseries_csv.rb
spec/urbanopt/urbanopt_scenario_spec.rb

- Added units to CSV reports
- updated rspec tests
[description here]

Added units to CSV reports

---

lib/measures/default_feature_reports/measure.rb
lib/urbanopt/scenario/default_reports/feature_report.rb
lib/urbanopt/scenario/default_reports/scenario_report.rb
lib/urbanopt/scenario/default_reports/schema/README.md
lib/urbanopt/scenario/default_reports/timeseries_csv.rb
spec/urbanopt/urbanopt_scenario_spec.rb

Save feature reports method

---

Gemfile
lib/urbanopt/scenario/default_reports/scenario_report.rb

Reverts urbanopt/urbanopt-scenario-gem#85
Ugh, don't know how that got merged, that was accidental.

Revert "Add function to save scenario-level results to sql file"

---

urbanopt-scenario-gem.gemspec

Specify Ruby version

---

lib/urbanopt/scenario/scenario_runner_osw.rb

List failed feature IDs after all simulations run.

list failed runs after scenario runs

---

lib/measures/default_feature_reports/measure.rb
lib/measures/default_feature_reports/measure.xml
lib/urbanopt/scenario/default_reports/distributed_generation.rb
lib/urbanopt/scenario/default_reports/feature_report.rb
lib/urbanopt/scenario/default_reports/scenario_report.rb
lib/urbanopt/scenario/default_reports/schema/scenario_csv_columns.txt
lib/urbanopt/scenario/scenario_runner_osw.rb

Adding power, net power, net energy and apparent power to timeseries results

Adding power, net power, net energy and apparent power to timeseries results

---

lib/measures/default_feature_reports/measure.rb
lib/urbanopt/scenario/default_reports/feature_report.rb
lib/urbanopt/scenario/default_reports/power_distribution.rb
lib/urbanopt/scenario/default_reports/scenario_report.rb
lib/urbanopt/scenario/default_reports/schema/scenario_schema.json
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
spec/urbanopt/urbanopt_scenario_spec.rb

- develop power distribution schema 
- opendss postprocessor enhancement

Add power distribution results to schema and reports

---

lib/urbanopt/scenario/default_reports/distributed_generation.rb

@rawadelkontar 
This address a couple bugs in the current distributed generation module.
1) total_storage_kwh was not made accessible
2) errors in to_hash

Multiplepv

---

Gemfile
urbanopt-scenario-gem.gemspec

Remove Rack specification from Gemfile, use gemspec to set Rack version

only specify Rack version once

---

CHANGELOG.md
lib/measures/default_feature_reports/measure.xml
lib/urbanopt/scenario/default_reports/power_distribution.rb
lib/urbanopt/scenario/default_reports/scenario_report.rb
lib/urbanopt/scenario/default_reports/timeseries_csv.rb
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
lib/urbanopt/scenario/version.rb
spec/urbanopt/urbanopt_scenario_spec.rb
urbanopt-scenario-gem.gemspec

- test with openstudio, 
- updated measure, 
- auto correct rubocop errors

prep for 0.2.0 release

---

lib/measures/default_feature_reports/measure.rb
lib/urbanopt/scenario/default_reports/reporting_period.rb
lib/urbanopt/scenario/default_reports/schema/scenario_schema.json

Add utility cost outputs
Added  utility cost outputs:
-  total utility cost
-  Utility cost by fuel type (Natural Gas, Electricity)

Added utility cost outputs to reports

---

CHANGELOG.md
lib/urbanopt/scenario/version.rb
urbanopt-scenario-gem.gemspec

prep for 0.3.0
fixes #115 
fixes #90

prep for 0.3.0

---

docs/package.json

Add minimist and dot-prop to dev dependencies, so we can set minimum version levels

bump minimist and dot-prop

---

urbanopt-scenario-gem.gemspec

update sqlite dependency

---

spec/files/mappers/TestMapper1.rb
spec/files/mappers/baseline.osw

updated ice storage measure names

updated ice storage measures names

---

CONTRIBUTING.md
LICENSE.md
RDOC_MAIN.md
README.md
Rakefile
docs/README.md
lib/urbanopt-scenario.rb
lib/urbanopt/scenario.rb
lib/urbanopt/scenario/default_reports.rb
lib/urbanopt/scenario/extension.rb
lib/urbanopt/scenario/logger.rb
lib/urbanopt/scenario/scenario_base.rb
lib/urbanopt/scenario/scenario_csv.rb
lib/urbanopt/scenario/scenario_datapoint_base.rb
lib/urbanopt/scenario/scenario_post_processor_base.rb
lib/urbanopt/scenario/scenario_post_processor_default.rb
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
lib/urbanopt/scenario/scenario_runner_base.rb
lib/urbanopt/scenario/scenario_runner_osw.rb
lib/urbanopt/scenario/scenario_visualization.rb
lib/urbanopt/scenario/simulation_dir_base.rb
lib/urbanopt/scenario/simulation_dir_osw.rb
lib/urbanopt/scenario/simulation_mapper_base.rb
lib/urbanopt/scenario/version.rb
spec/files/example_feature_file.rb
spec/files/mappers/TestMapper1.rb
spec/spec_helper.rb
spec/urbanopt/urbanopt_scenario_reports_spec.rb
spec/urbanopt/urbanopt_scenario_spec.rb

add tm symbol

---

lib/urbanopt/scenario/scenario_visualization.rb
spec/urbanopt/urbanopt_scenario_reports_spec.rb

Adds headers from feature/scenario reports without units.

Add unitless header values

---

urbanopt-scenario-gem.gemspec

Need to have Core & Reporting gems in the gemspec or else other gems won't work. Oops.

Restore gemspec dep reqs that I broke

---

CHANGELOG.md
CONTRIBUTING.md
Gemfile
LICENSE.md
README.md
Rakefile
lib/urbanopt-scenario.rb
lib/urbanopt/scenario.rb
lib/urbanopt/scenario/default_reports.rb
lib/urbanopt/scenario/extension.rb
lib/urbanopt/scenario/logger.rb
lib/urbanopt/scenario/scenario_base.rb
lib/urbanopt/scenario/scenario_csv.rb
lib/urbanopt/scenario/scenario_datapoint_base.rb
lib/urbanopt/scenario/scenario_post_processor_base.rb
lib/urbanopt/scenario/scenario_post_processor_default.rb
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
lib/urbanopt/scenario/scenario_runner_base.rb
lib/urbanopt/scenario/scenario_runner_osw.rb
lib/urbanopt/scenario/scenario_visualization.rb
lib/urbanopt/scenario/simulation_dir_base.rb
lib/urbanopt/scenario/simulation_dir_osw.rb
lib/urbanopt/scenario/simulation_mapper_base.rb
lib/urbanopt/scenario/version.rb
spec/files/Gemfile
spec/urbanopt/urbanopt_scenario_reports_spec.rb
spec/urbanopt/urbanopt_scenario_spec.rb
urbanopt-scenario-gem.gemspec

prep for 0.4.0 release and rubocop

prep for release and rubocop

---

CHANGELOG.md
lib/urbanopt/scenario/scenario_post_processor_default.rb
lib/urbanopt/scenario/version.rb
spec/urbanopt/urbanopt_scenario_spec.rb

fix how datapoint dirs are found for sqlite scenario results processing

---

CHANGELOG.md
README.md
lib/urbanopt/scenario/version.rb

version 0.4.2 - bug fix for sqlite reporting

prep 0.4.2

---

.github/pull_request_template.md

Changes the PR template to include keyword to automatically close the related issue when the PR is merged.

use issue-closing keyword and remove period

---

lib/urbanopt/scenario/scenario_post_processor_default.rb
lib/urbanopt/scenario/version.rb

The existing query wasn't actually looping through the feature sql files. Simplified and brought the request inside the loop, now the values are adding up properly.

fix bug in query for scenario_db output

---

Gemfile
spec/files/Gemfile
urbanopt-scenario-gem.gemspec

bump dependencies

---

docs/package-lock.json
docs/package.json

bump version of package dependency

Dependabot ini to 2.0.0

---

lib/urbanopt/scenario/scenario_csv.rb
urbanopt-scenario-gem.gemspec

Adds bundle_path from runner.conf file or from root directory bundle folder.

Bundle bug

---

Gemfile
spec/files/Gemfile
urbanopt-scenario-gem.gemspec

updating to ruby27

---

lib/urbanopt/scenario/scenario_csv.rb

fixing bundle loading issue when project name has urbanopt in it

---

.rubocop.yml

update rubocop to v4 #214

---

CHANGELOG.md
lib/urbanopt/scenario/logger.rb
lib/urbanopt/scenario/scenario_csv.rb
lib/urbanopt/scenario/scenario_datapoint_base.rb
lib/urbanopt/scenario/scenario_post_processor_default.rb
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
lib/urbanopt/scenario/scenario_runner_osw.rb
lib/urbanopt/scenario/scenario_visualization.rb
lib/urbanopt/scenario/simulation_dir_base.rb
lib/urbanopt/scenario/simulation_dir_osw.rb
lib/urbanopt/scenario/version.rb
spec/files/Gemfile
spec/files/mappers/TestMapper1.rb
spec/urbanopt/urbanopt_scenario_reports_spec.rb
spec/vis_test/baseline_scenario/scenarioData.js
urbanopt-scenario-gem.gemspec

prep_0.6.2

---

CHANGELOG.md
Gemfile
lib/urbanopt/scenario/version.rb
urbanopt-scenario-gem.gemspec

* Reminder to clean-up the gemfile before merging!

updates for OpenStudio 3.3

---

Gemfile
lib/urbanopt/scenario/scenario_post_processor_opendss.rb
spec/files/opendss_outputs/opendss/json_files/Model.json

adding opendss fields from Model.json back into the URBANopt reports

expanding opendss reporting

---

.github/workflows/nightly_build.yml
Gemfile
README.md
docs/package-lock.json
spec/spec_helper.rb
urbanopt-scenario-gem.gemspec

Adds Github action to run all tests via rspec and report coverage via Coveralls. Syntax is copied from geojson-gem.

GitHub actions coveralls

---

lib/urbanopt/scenario/scenario_visualization.rb
spec/urbanopt/urbanopt_scenario_reports_spec.rb
spec/vis_test/baseline_scenario/scenarioData.js
spec/vis_test/scenarioData.js

qaqc processing for visualization js files. Fixes #252

Qaqc visualizing

---

.github/workflows/nightly_build.yml

Update CI to use OpenStudio 3.5.1

update gha ci for openstudio 3.5.1

---

lib/urbanopt/scenario/scenario_post_processor_opendss.rb

- explicitly check if bld_load is empty, not just whether it exists
- Also allow the rnm syntax of feature id being written to Model.json

Improve RNM -> OpenDSS workflow

---

urbanopt-scenario-gem.gemspec

Argh, bitten by versioning again! At least this time it was my fault so it's easy to fix. 🤦

enforce using sqlite3 v1.6 because 1.7 requires ruby3

---

.github/workflows/nightly_ci_build.yml
Gemfile
LICENSE.md
doc_templates/LICENSE.md
doc_templates/copyright_erb.txt
lib/urbanopt/scenario/version.rb
urbanopt-scenario-gem.gemspec

Support os37 for testing

---

Gemfile
lib/urbanopt/scenario/scenario_csv.rb
spec/urbanopt/urbanopt_scenario_spec.rb

* Patches #274
* Companion PR:
* https://github.com/NREL/openstudio-extension-gem/pull/190 
[description here]

Fixup openstudio-extension-gem sub bundle errors

---

.github/workflows/nightly_ci_build.yml
CHANGELOG.md
Gemfile
LICENSE.md
doc_templates/LICENSE.md
doc_templates/copyright_erb.txt
lib/urbanopt/scenario/logger.rb
lib/urbanopt/scenario/scenario_csv.rb
lib/urbanopt/scenario/scenario_datapoint_base.rb
lib/urbanopt/scenario/scenario_runner_osw.rb
lib/urbanopt/scenario/simulation_dir_base.rb
lib/urbanopt/scenario/simulation_dir_osw.rb
lib/urbanopt/scenario/version.rb
spec/files/Gemfile
spec/urbanopt/urbanopt_scenario_spec.rb
spec/vis_test/baseline_scenario/scenarioData.js
spec/vis_test/scenarioData.js
urbanopt-scenario-gem.gemspec

- Update to OpenStudio 3.9
- Necessitates an update to Ruby 3.2.2
- Temporarily use branches of OS dependencies during testing

Upgrade to OpenStudio 3.9 and Ruby 3.2.2
